const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8'));
const index = fs.readFileSync(path.join(__dirname, '..', 'views', 'index.ejs'), 'utf8');
const courseView = fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'course.ejs'), 'utf8');
const todoView = fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'todo.ejs'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');
const client = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8');

assert.ok(pkg.dependencies['better-sqlite3'], 'Better SQLite should be installed for secure persistent storage.');
assert.match(index, /<script src="\/app\.js"><\/script>/, 'The page should load the client-side auth tab script.');
assert.match(index, /\['about', 'support', 'privacy', 'terms', 'understand'\]/, 'Public information pages should render through the shared shell.');
assert.match(courseView, /inline-create-form.*hidden/, 'The inline event form should stay hidden until the Create event action is triggered.');
assert.match(todoView, /data-live-todo-form/, 'The personal todo add form should be wired for browser-side updates.');
assert.match(todoView, /toggle-task-form/, 'The personal todo should support browser-side add/toggle updates without a full page refresh.');
assert.match(app, /items\/reorder/, 'Course tasks should have a reorder endpoint.');
assert.match(client, /course:items-reordered/, 'Course task reordering should update live over websockets.');
assert.match(client, /response\.redirected/, 'Client navigation should not render redirected content at the requested URL.');
assert.match(app, /\/org\/:id\/admin\/:tab\?/, 'Groups should expose tabbed admin routes.');
assert.match(app, /render\(request, response, 'admin', \{/, 'Admin should render through the page renderer.');
assert.match(app, /selectedOrg: org,/, 'Admin should render with group context.');
assert.match(app, /\/org\/:id\/admin\/share/, 'Sharing should have its own admin mutation.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'moderation', 'comments.js'), 'utf8'), /admin\/comments\/:commentId\/review/, 'Admins should be able to mark comments reviewed.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'admin.ejs'), 'utf8'), /Review new comments/, 'The admin page should expose the moderation queue.');
assert.match(app, /admin\/reports\/:reportId\/action/, 'Admins should have report action handling.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'admin.ejs'), 'utf8'), /Mod Action/, 'Reports should expose removal and moderation actions.');
assert.match(app, /\['remove', 'remove-moderate', 'warn', 'ban', 'close'\]/, 'Report moderation should support warnings.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'warning-modal.ejs'), 'utf8'), /data-warning-modal/, 'Warnings should appear in a persistent modal.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'moderation', 'comments.js'), 'utf8'), /\['admin', 'moderator'\]/, 'Reports should notify admins and moderators.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'admin.ejs'), 'utf8'), /reported-content/, 'Reports should show the reported content.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'moderation', 'comments.js'), 'utf8'), /successMessage: 'Report submitted/, 'Report submission should return a success message.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8'), /notification:added/, 'Notifications should arrive over websockets.');
assert.match(app, /notifications\/:notificationId\/read/, 'Users should be able to mark notifications read.');
assert.match(app, /members\/:userId\/repercussion/, 'Admins should have member conduct actions.');
assert.match(app, /members\/:userId\/access/, 'Admins should be able to change member access.');
assert.match(app, /\['viewer', 'editor', 'moderator'\]/, 'Member access should support viewer, editor, and moderator.');
assert.match(app, /'moderator', 'admin'/, 'Member access should support assigning admins.');
assert.match(app, /member\.role === 'moderator' && !\['mod', 'report'\]/, 'Moderators should be limited to moderation and reports tabs.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'people.ejs'), 'utf8'), /Ban permanently/, 'People should expose permanent bans.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'people.ejs'), 'utf8'), /Update access/, 'People should expose access changes.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'topbar.ejs'), 'utf8'), /notification-popover/, 'The topbar should expose notifications.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'course.ejs'), 'utf8'), /filter\(comment => !comment\.reported\)\.length/, 'Comment counts should exclude removed or reported comments.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8'), /notification-waterfall-out/, 'Notification dismissal should animate out.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8'), /notification-item\.unread/, 'Notification reads should update the UI live.');
assert.match(app, /app\.get\('\/privacy'/, 'The privacy policy should have a public route.');
assert.match(app, /app\.get\('\/terms'/, 'The terms should have a public route.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'understand.ejs'), 'utf8'), /informational only/, 'The student guide should clearly disclaim legal force.');
assert.match(fs.readFileSync(path.join(__dirname, '..', 'views', 'partials', 'privacy.ejs'), 'utf8'), /does not currently collect email addresses/, 'Privacy should match current email behavior.');

console.log('smoke checks passed');
